<?php

 // Auto generated by wpfluent Installer.

 return array (
  'name' => 'Fluent Query Logger',
  'slug' => 'fluent-query-logger',
  'domain_path' => '/language',
  'text_domain' => 'fluent-query-logger',
  'hook_prefix' => 'fluent-query-logger',
  'rest_namespace' => 'fluent-query-logger',
  'rest_version' => 'v2',
  'env' => 'dev',
);
